# This is a basic workflow to help you get started with Actions

name: FeedCheck

# Action の実行条件
on:
  # main ブランチに push/PR された場合に実行
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 手動による実行を許可
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # job の実行になるべく最新の Ubuntu イメージを利用
    runs-on: ubuntu-latest

    # job の実行ステップ
    steps:
      # $GITHUB_WORKSPACE のパスにリポジトリをチェックアウト
      - uses: actions/checkout@v2

      # XMLLint のインストール
      - name: Install xmllint
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt -y install libxml2-utils

      # XMLLint の実行
      - name: XML lint check
        run: |
          if ! find "$GITHUB_WORKSPACE" -name "*.atom" | xargs xmllint >/dev/null; then
            echo >&2 'XML lint check failed.'; exit 1
          fi
          echo 'XML lint check passed.'
